name: Build
on:
  pull_request:
    branches:
      - '*'
jobs:
  # TODO: Add some health check jobs
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        hadoop: ["3.2.0"]
        hive-metastore: ["3.0.0"]
    env:
      HIVE_METASTORE_VERSION: ${{ matrix.hive-metastore }}
      HADOOP_VERSION: ${{ matrix.hadoop }}
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: |
          docker build \
            --build-arg METASTORE_VERSION=$HIVE_METASTORE_VERSION \
            --build-arg HADOOP_VERSION=$HADOOP_VERSION \
            -t vmalashkov/apache-hive-metastore:$HIVE_METASTORE_VERSION-h${HADOOP_VERSION} .